apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: front
    spec:
      nodeSelector:
        env: test
      containers:
        - name: front
          image: team4devops/ecommerce-frontend-ui:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              
      

